name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: 'Test on Node v${{ matrix.node }} ${{ matrix.os.name }} ${{ matrix.arch }}'
    runs-on: ${{ matrix.os.name }}-${{ matrix.os.version }}

    strategy:
      matrix:
        os:
          - name: Windows
            version: 2019
        node: ['16']
        arch: [x64]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: 'Install Linux dependencies'
        if: ${{ matrix.os.name == 'Ubuntu' }}
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev
      - name: 'Install npm@^8'
        run: npm install --global npm@8.3.1
      - name: Install
        run: npm ci --unsafe-perm
      - name: Build
        run: npm run build_tests
      - name: Install chrome
        uses: browser-actions/setup-chrome@latest
        with:
          run: chrome --version
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run testPuppeteer