name: Create tagged release
on:
  push:
    tags:
      - v*.*.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: 'Install npm@^8'
        run: npm install --global npm@8.3.1
      - name: Install
        run: npm ci --unsafe-perm
      - name: Publish tagged release to npm
        run: |
          npm i clean-package -g
          npm whoami
          npm run build
          npm run publish_package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}